version: '3.8'
services:
  app:
    build: .
    ports:
      - '${PORT}:8000'
    networks:
      - mynetwork
    depends_on:
      - db
      - test-db
    env_file:
      - .env.dev
  db:
    image: postgres:16-alpine
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/postgresql/data
    env_file: 
      - .env.dev
  test-db:
    image: postgres:16-alpine
    networks:
      - mynetwork
    volumes:
      - test-db:/var/lib/postgresql/data
    env_file: 
      - .env.test
volumes:
  db:
    driver: local
  test-db:
    driver: local
networks:
  mynetwork:
    attachable: true